image: archlinux/base:latest

before_script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S gcc make qt5-base util-linux

stages:
    - build
    - test

gcc:
    stage: build
    script:
    - export CC=gcc
    - export CXX=g++
    - make release -j$(nproc)
    artifacts:
        paths:
        - rotwkl

tests:
    stage: test
    script:
    - ci/verify
