[launcher]
swap = "true"

[game]
path = ""

[edain]
available = "false"

[botta]
available = "false"
path = ""

[mount]
automatic = "false"
mount_exe = ""
disc_image = ""
mount_flags = ""
umount_flags = ""
mount_cmd = ""
umount_cmd = ""
