[[enable]]
name = "_____english_ini.big"
checksum = "789b5703c0b7f3650083e98e0c3be64e"
extension = "disabled"

[[enable]]
name = "_____voice_english.big"
checksum = "2fd8fb943c0b23f796320fd0a659dbc5"
extension = "disabled"

[[enable]]
name = "____edain_maps.big"
checksum = "60859f6f532308ac789dffb22bf671df"
extension = "big.bak"

[[enable]]
name = "___edain_apt_widescreen.big"
checksum = "1b279cce80908532353f2a339f086cd6"
extension = "big.bak"

[[enable]]
name = "__edain_apt.big"
checksum = "aff5650bdb16f7313b7ac3fff714e9a0"
extension = "big.bak"

[[enable]]
name = "__edain_data.big"
checksum = "6fa677548534d461844c11cd4f322939"
extension = "big.bak"

[[enable]]
name = "__edain_german.big"
checksum = "a24531c93645ba9e48c4262b838b7154"
extension = "big.bak"

[[enable]]
name = "__edain_music.big"
checksum = "bebd25f429aad91327d68306ab51c9f6"
extension = "big.bak"

[[enable]]
name = "__edain_terrain.big"
checksum = "d9612b94a572c40a5a4afc32769d1358"
extension = "big.bak"

[[enable]]
name = "__edain_textures1.big"
checksum = "28885fa54988722e440502dbf1f07f75"
extension = "big.bak"

[[enable]]
name = "__edain_textures2.big"
checksum = "26f08eb619dd65804b60e63dc8820b25"
extension = "big.bak"

[[enable]]
name = "__edain_w3d.big"
checksum = "f4622dbf4b3251d80ff7215d52fe2c2a"
extension = "big.bak"

[[disable]]
name = "##########202_v8.0.0.big"
checksum = "27ad912c69b83772cf62f24093450109"
extension = "disabled"

[[disable]]
name = "########202_v6.0.0.big"
checksum = "30d4ffc5ff682a1638264f58010d560f"
extension = "disabled"

[[disable]]
name = "######202_v5.0.1.big"
checksum = "39432b55bd6ec358d704056d118b3a93"
extension = "disabled"

[[disable]]
name = "#####202_v5.0.0.big"
checksum = "bf7bb2783bdf17f799ecc9eadd607496"
extension = "disabled"

[[disable]]
name = "####unofficialpatch202_v3.6.1.big"
checksum = "b6ee0519e040d5a1234e021e40b6df58"
extension = "disabled"

[[disable]]
name = "###unofficialpatch202_v3.6.0.big"
checksum = "d2689ed3c83d88fee455b82630f88a5c"
extension = "disabled"

[[disable]]
name = "##unofficialpatch202_v3.0.5.2.big"
checksum = "bfa61d1dd53a8cb8bf2b7f34fb8b5dc4"
extension = "disabled"

[[disable]]
name = "#unofficialpatch202_v3.0.5.1.big"
checksum = "178de3c576f0ee854bebee13929cc70c"
extension = "disabled"

[[disable]]
name = "______________unofficialpatch202_v3.0.5.0.big"
checksum = "7f10f80d17b130d288d1249ace03323e"
extension = "disabled"

[[disable]]
name = "_____________unofficialpatch202_v3.0.4.0.big"
checksum = "2ae5a157f7e5a60adcf163d1fd4c5631"
extension = "disabled"

[[disable]]
name = "____________unofficialpatch202_v3.0.3.1.big"
checksum = "5acbf2053c526e979bbe7c168d67d894"
extension = "disabled"

[[disable]]
name = "___________unofficialpatch202_v3.0.3.0.big"
checksum = "b7a6636956afea218e0411fff01f97f3"
extension = "disabled"

[[disable]]
name = "__________unofficialpatch202_v3.0.2.2.big"
checksum = "d5b65c9b27a1d3346ace2388a9b34d57"
extension = "disabled"

[[disable]]
name = "_________unofficialpatch202_v3.0.2.1.big"
checksum = "5c4e4b5a2ce07efab1062ac6c1678711"
extension = "disabled"

[[disable]]
name = "________unofficialpatch202_v3.0.2.0.big"
checksum = "c8aa03fce53654d41e8dc1faf42f30bc"
extension = "disabled"

[[disable]]
name = "_______unofficialpatch202_v3.0.1.2.big"
checksum = "60b441752572ef83c320e058eedb03bb"
extension = "disabled"

[[disable]]
name = "______unofficialpatch202_v3.0.1.1.big"
checksum = "4151f6a535870cd5baa36cfe2a4abb12"
extension = "disabled"

[[disable]]
name = "_____unofficialpatch202_v3.0.1.0.big"
checksum = "acb8d16a9260d712a35282a84bf0a61c"
extension = "disabled"

[[disable]]
name = "____unofficialpatch202_v3.0.0.1.big"
checksum = "2cc434d4e24ddc1633db42a932c55b63"
extension = "disabled"

[[disable]]
name = "___unofficialpatch202_v3.0.0.0.big"
checksum = "7ec6b049f4eb3477242ef348590b12dd"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.0.0.big"
checksum = "d0a15323375eba0aaaaef12e9feb0352"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.0.1.big"
checksum = "a410ff55f3d293d1b7289f36d98d4cf3"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.1.0.big"
checksum = "33cea1b51697fcff237d6f736457434a"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.1.1.big"
checksum = "6ce4105e45dbe544c0629885e2d1474f"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.1.2.big"
checksum = "39a50f8ab0dcb9f4783c49024c3d1d9d"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.2.0.big"
checksum = "0be8f48c327222be5506725408e31583"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.2.1.big"
checksum = "ae405e6483424c046cd21f4b994ee819"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.2.2.big"
checksum = "dba29fa69ba9b269b7e915b53c71c73c"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.3.0.big"
checksum = "415469e1deb51b405f521be7597b2484"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.3.1.big"
checksum = "03bf314bceb94b9f33fef4e577f1dd4c"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.4.0.big"
checksum = "9a43ab09007c4ea4c35e732e7026ea08"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.5.0.big"
checksum = "5742c51324588b56aa276a11a2be76aa"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.5.1.big"
checksum = "a03f7c31613c53438827d19999d6f83c"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.5.2.big"
checksum = "e9e5927e253592c09fe637c9ac41a9e3"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.0.6.big"
checksum = "aa785c6888e905f26cce7df2deebd751"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.6.1.big"
checksum = "4e2b54e0d9e8977ed1e75d8b637c6d8f"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v3.6.2.big"
checksum = "b7aa9bf40ce074cd98488d7d07853750"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v5.0.0.big"
checksum = "d6e493a21840ab3690e7a9e47a3ca9f7"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v5.0.1.big"
checksum = "c8db9cfa955a8aa971291d9c539aef38"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v6.0.0.big"
checksum = "d9dc2d3e244cffad31c49fe673b7cf96"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v8.0.0.big"
checksum = "29f18a1f784564494f32e502276b6992"
extension = "disabled"

[[disable]]
name = "#########202_v7.0.0.big"
checksum = "75eea4740fc6ab777ef576291e11f020"
extension = "disabled"

[[disable]]
name = "lang/englishstrings202_v7.0.0.big"
checksum = "f00ac12b0a99cbf95c6bd0019aebe322"
extension = "disabled"

[[disable]]
name = "lang/English.big"
checksum = "6e821860d8f6cb87212eafd64df47821"
extension = "disabled"

[[disable]]
name = "lang/englishpatch201.big"
checksum = "640671ec736134eccf112e83659cf6d2"
extension = "disabled"

[[swap]]
    [swap.activate]
        name = "game.dat"
        checksum = "84659690d2b47506bb23b2b43bd3b238"
        disabled = "game.other"
    [swap.deactivate]
        name = "game.dat"
        checksum = "fbff091f6139eb05dc012d834e3eeb74"
        disabled = "game.other"
    [swap.activate]
        name = "asset.dat"
        checksum = "e4573b34fcf23f184a53c81ffe3f84b3"
        disabled = "asset2.dat"
    [swap.deactivate]
        name = "asset.dat"
        checksum = "f1333838f8a68ce2c318c421218465d8"
        disabled = "asset2.dat"
