[[enable]]
name = _____english_ini.big
checksum = p(Ÿß
extension = disabled

[[enable]]
name = _____voice_english.big
checksum = p(Ÿß
extension = disabled

[[enable]]
name = ____edain_maps.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = ___edain_apt_widescreen.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_apt.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_data.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_german.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_music.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_terrain.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_textures1.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_textures2.big
checksum = p(Ÿß
extension = big.bak

[[enable]]
name = __edain_w3d.big
checksum = p(Ÿß
extension = big.bak

[[disable]]
name = ########202_v6.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ######202_v5.0.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = #####202_v5.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ####unofficialpatch202_v3.6.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ###unofficialpatch202_v3.6.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ##unofficialpatch202_v3.0.5.2.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = #unofficialpatch202_v3.0.5.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ______________unofficialpatch202_v3.0.5.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = _____________unofficialpatch202_v3.0.4.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ____________unofficialpatch202_v3.0.3.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ___________unofficialpatch202_v3.0.3.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = __________unofficialpatch202_v3.0.2.2.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = _________unofficialpatch202_v3.0.2.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ________unofficialpatch202_v3.0.2.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = _______unofficialpatch202_v3.0.1.2.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ______unofficialpatch202_v3.0.1.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = _____unofficialpatch202_v3.0.1.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ____unofficialpatch202_v3.0.0.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = ___unofficialpatch202_v3.0.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.0.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.1.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.1.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.1.2.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.2.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.2.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.2.2.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.3.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.3.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.4.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.5.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.5.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.5.2.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.0.6.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.6.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v3.6.2.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v5.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v5.0.1.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v6.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = #########202_v7.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishstrings202_v7.0.0.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/English.big
checksum = p(Ÿß
extension = disabled

[[disable]]
name = lang/englishpatch201.big
checksum = p(Ÿß
extension = disabled

[[swap]]
    [swap.activate]        name = game.dat
        checksum = p(Ÿß
    [swap.deactivate]        name = game.dat
        checksum = p(Ÿß
