#!/bin/bash

set -e

export CC="$msys_bin""/gcc.exe"
export CXX="$msys_bin""/g++.exe"

project_dir="C:/projects/rotwkl"
qt_path="C:/Qt/5.13/mingw73_64"
qt_bin="$qt_path""/bin"
msys_bin="C:/msys64/mingw64/bin"
artifact_dir="rotwkl"
archive="$artifact_dir"".zip"

declare -a dlls

dlls+=("$qt_bin""/Qt5Core.dll")
dlls+=("$qt_bin""/Qt5Gui.dll")
dlls+=("$qt_bin""/Qt5Svg.dll")
dlls+=("$qt_bin""/Qt5Widgets.dll")
dlls+=("$msys_bin""/libgcc_s_seh-1.dll")
dlls+=("$msys_bin""/libstdc++-6.dll")
dlls+=("$msys_bin""/libwinpthread-1.dll")

pacman --noconfirm -Syu
pacman --noconfirm --needed -S make gcc zip mingw-w64-x86_64-toolchain mingw-w64-x86_64-openssl

cd "$project_dir"

make release QT_PATH="$qt_path"

mkdir "$artifact_dir"
cp -r {images,toml,xml,rotwkl} "$artifact_dir"/

for ddl in "${dlls[@]}" do
    cp dll "$artifact_dir"
done

zip -r rotwkl.zip "$artifact_dir"
